### ISSUE TITLE
error while trying to render maps

### ISSUE THREAD

**Issue by adilevi1** [IsraelHikingMap/Map#156] opened 2017-08-17 06:35 UTC
When running CreateOruxMap.py using maperitive,  maperitive opens and starts running, but I get the following error in line 57, in <module>
TypeError: __init__() takes exactly 1 argument (4 given).

Also, What is the command line for running this script on Linux?

**Comment by HarelM** [comment] 2017-08-17 09:59
Maperitive as far as we know does not run on Linux, Although we didn't fully tried to make it work so it might be possible, but we currently do not have any plans to do so.
@zstadler can probably better help you with the above line of code.
Did you make sure to follow the step by step instruction of the [repository's readme](https://github.com/IsraelHikingMap/Map#building-the-map)?

**Comment by adilevi1** [comment] 2017-08-18 11:21
Thanks, Harel. Yes, I followed all the steps. It looks like the spript is trying to initizlize GenIsraelHikingTiles.IsraelHikingTileGenCommand, which indeed takes a singele argument in line 65.
def __init__(self):
@zstadler, What am I missing?

**Comment by zstadler** [comment] 2017-08-18 11:41
I should have deleted `CreateOruxMap.py` and `CreateMtbMap.py` as they are no longer used or working.  :-(

The tile creation is done by `CreateAllMaps.py`, which also handles retrieving the data and incremental map updates. By default it creates the Hiking map, the Biking map, and the Trails overlay. You can select the necessary phases by editing [the definition of the `phases` list](https:../blob/master/Scripts/Maperipy/CreateAllMaps.py#L134-L138).

If you just want to setup Maperitive without any tile generation, please use [`Scripts/Maperitive/IsraelHiking.mscript`](https:../blob/master/Scripts/Maperitive/IsraelHiking.mscript)

Note that we've never tried Maperitive on Linux.

**Comment by adilevi1** [comment] 2017-08-20 05:56
Thanks! It runs well.
Now I've got a new issue: I've black areas in the map.

![blackhole](https://user-images.githubusercontent.com/31091314/29492473-397f5fe4-8585-11e7-92da-3f9b498832a6.jpg)

**Comment by zstadler** [comment] 2017-08-20 11:43
It seems like some of our textures are missing from the Maperitive installation.

Please run `Scripts\Maperipy\IsraelHikingInstallOnce.py` in order to
```text
# Perform one-time installation tasks:
# 1. Copy DEM files to Maperitive installation
# 2. Copy additional icons to the Maperitive installation
# 3. Set map decoration defaults
# 4. Update Mobile Atlas Creator files, including ajdusting local map sources path
```

Yes, the instructions for [building the map](../blob/master/README.md#building-the-map) should be updated. I would appreciate if you could do that as a pull-request.

**Comment by zstadler** [comment] 2017-10-02 20:05
@adilevi1,
 If the issue is resolved, please close it.

**Comment by bnayalivne** [comment] 2017-10-07 07:10
@adilevi1 can you update the readme file how you managed to build the map on linux?
I've run the following on Maperitive:
run-python "~/IsraelHikingMap/Scripts/Maperipy/IsraelHikingInstallOnce.py"

And I get the following error:
> run-python "~/IsraelHikingMap/Scripts/Maperipy/IsraelHikingInstallOnce.py"
   Value cannot be null.
   Parameter name: method

**Comment by zstadler** [comment] 2017-10-07 20:27
@bnayalivne ,

Please open a separate issue for running IsraelHikingInstallOnce.py on Linux so I can respond separately.

**Comment by zstadler** [comment] 2018-03-02 15:12
Closed for lack of response

**Closed by zstadler** 2018-03-02 15:12 UTC
